<?php

/**
 * This is the model base class for the table "post".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Post".
 *
 * Columns in table "post" available as properties of the model,
 * followed by relations of table "post" available as properties of the model.
 *
 * @property integer $idPost
 * @property string $titulo
 * @property string $texto
 * @property string $autor
 * @property string $data
 * @property string $imagem
 * @property integer $usuario_id
 * @property string $categoria
 *
 * @property Comentario[] $comentarios
 * @property Usuario $usuario
 */
abstract class BasePost extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'post';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Post|Posts', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('idPost, titulo, texto, autor, data, usuario_id, categoria', 'required'),
			array('idPost, usuario_id', 'numerical', 'integerOnly'=>true),
			array('titulo, autor, categoria', 'length', 'max'=>100),
			array('imagem', 'length', 'max'=>45),
			array('imagem', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idPost, titulo, texto, autor, data, imagem, usuario_id, categoria', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'comentarios' => array(self::HAS_MANY, 'Comentario', 'post_idPost'),
			'usuario' => array(self::BELONGS_TO, 'Usuario', 'usuario_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idPost' => Yii::t('app', 'Id Post'),
			'titulo' => Yii::t('app', 'Titulo'),
			'texto' => Yii::t('app', 'Texto'),
			'autor' => Yii::t('app', 'Autor'),
			'data' => Yii::t('app', 'Data'),
			'imagem' => Yii::t('app', 'Imagem'),
			'usuario_id' => null,
			'categoria' => Yii::t('app', 'Categoria'),
			'comentarios' => null,
			'usuario' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idPost', $this->idPost);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('texto', $this->texto, true);
		$criteria->compare('autor', $this->autor, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('usuario_id', $this->usuario_id);
		$criteria->compare('categoria', $this->categoria, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}