<?php

/**
 * This is the model base class for the table "usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "usuario" available as properties of the model,
 * followed by relations of table "usuario" available as properties of the model.
 *
 * @property integer $idUsuario
 * @property string $username
 * @property string $senha
 *
 * @property Post[] $posts
 */
abstract class BaseUsuario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usuario|Usuarios', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('idUsuario, username, senha', 'required'),
			array('idUsuario', 'numerical', 'integerOnly'=>true),
			array('username, senha', 'length', 'max'=>45),
			array('idUsuario, username, senha', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'posts' => array(self::HAS_MANY, 'Post', 'usuario_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idUsuario' => Yii::t('app', 'Id Usuario'),
			'username' => Yii::t('app', 'Username'),
			'senha' => Yii::t('app', 'Senha'),
			'posts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idUsuario', $this->idUsuario);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('senha', $this->senha, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}