<?php

/**
 * This is the model base class for the table "comentario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comentario".
 *
 * Columns in table "comentario" available as properties of the model,
 * followed by relations of table "comentario" available as properties of the model.
 *
 * @property integer $idComent
 * @property string $autor
 * @property string $texto
 * @property integer $post_idPost
 * @property string $email
 * @property string $data
 *
 * @property Post $postIdPost
 */
abstract class BaseComentario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comentario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comentario|Comentarios', $n);
	}

	public static function representingColumn() {
		return 'autor';
	}

	public function rules() {
		return array(
			array('idComent, autor, post_idPost, email, data', 'required'),
			array('idComent, post_idPost', 'numerical', 'integerOnly'=>true),
			array('autor, email', 'length', 'max'=>100),
			array('texto', 'safe'),
			array('texto', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idComent, autor, texto, post_idPost, email, data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'postIdPost' => array(self::BELONGS_TO, 'Post', 'post_idPost'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idComent' => Yii::t('app', 'Id Coment'),
			'autor' => Yii::t('app', 'Autor'),
			'texto' => Yii::t('app', 'Texto'),
			'post_idPost' => null,
			'email' => Yii::t('app', 'Email'),
			'data' => Yii::t('app', 'Data'),
			'postIdPost' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idComent', $this->idComent);
		$criteria->compare('autor', $this->autor, true);
		$criteria->compare('texto', $this->texto, true);
		$criteria->compare('post_idPost', $this->post_idPost);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('data', $this->data, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}